phraseapp:
  access_token: "75caf899a241214d7d9ab63230d3e9e82f557bbec96f3b75fd29b4ebdb8dfdc9"
  push:
    sources:
      file: ./en-gb/<tag>.php
      params:
        file_format: php
  pull:
    targets:
      # authentication
      -
        file: ./<locale_name>/authentication.php
        params:
          tag: "authentication"
          file_format: php